/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_torclient_free: (a: number, b: number) => void;
export const __wbg_torclientoptions_free: (a: number, b: number) => void;
export const init: () => [number, number];
export const torclient_close: (a: number) => any;
export const torclient_fetch: (a: number, b: number, c: number, d: any) => any;
export const torclient_new: (a: number) => any;
export const torclientoptions_new: (a: number, b: number, c: number, d: number) => number;
export const torclientoptions_snowflakeWebRtc: (a: number, b: number) => number;
export const torclientoptions_withStorage: (a: number, b: any) => number;
export const setLogCallback: (a: any) => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const wasm_bindgen__closure__destroy__h915bf6b7ffb6c7f3: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h0222088af2013b64: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hd65abcb002037431: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h360923ea2bfa4551: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h108123f683c1d79d: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h692dfa7102be6671: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hfd4ce4d6641069e0: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
